### ISSUE TITLE
conversion of PATHS p annotations

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/paths-longtexts-dev#2]
This is really a conversation (rather than a problem) that I wish to put on GitHub for documentation.  It looks like the p spans in the original PATHS encoding were not always preserved as p spans in CS GitDox editions.  (Compare https://github.com/paths-erc/coptic-texts/blob/master/cc0407.xml with life.aphou 1 & 2.) 

In the case of Life of Aphou, the p spans from PATHS may be meaningful. They seem to correspond most of the time to ekthesis or to marginal notations in the manuscript as noted by the [original editor Rossi](https://suciualin.files.wordpress.com/2012/01/rossi-i-papiri-copti-1-3-trascrizione-di-tre-manoscritti-copti-del-museo-egizio-di-torino.pdf).

It looks like lb in GitDox corresponds to PATHS p spans.

I would like to:

- Rename lb to something else since they are not line breaks. The best solutions I can come up with are a) p_source (fill all spans with "PATHS") or b) p_PATHS (fill spans with p) or c) s spans (but I think we use those in TEI for translation). I welcome other better solutions

- Annotate new p spans according to the ekthesis in the Rossi edition (as per our usual guidelines of ekthesis=new chapter) and thus abandon the p spans in the doc currently.  

What do you think?

**Comment by ctschroeder** [comment]
wait I think the PATHS p spans are sentences.

**Comment by amir-zeldes** [comment]
It's possible the p became lb, especially if the input file had one p per line. The final p's in the release were just a proxy for chapters, and were adjusted to match the automatic sentence spans, since paragraphs must properly nest sentences. The unnumbered p's in the data did not seem to align with sentences, so I didn't think too much about them, but I think the numbered p's in the documents that had them were meaningful, and were used for chapters in the data.

**Comment by ctschroeder** [comment]
﻿Thanks for the quick response!

The texts I’m looking at were not released in the fall. Some documents like Life of Aphou don’t have chapters (except the ones I’m adding right now). 

So it sounds like the p spans in the texts that were not released still come from you as proxies that can be changed?

Pls let me know if you have objections/suggestions about renaming the lb/paths p spans and about the new p spans. 

Thank you!!

**Comment by amir-zeldes** [comment]
No objections to anything! The only thing I think is probably meaningful is the numbered paragraphs (I think two documents had them and two didn't)

**Comment by ctschroeder** [comment]
Ok in Aphou 1 I've renamed the lb's p_source (filling the cells with PATHS), added chapter_n based on ekthesis in the print edition (Rossi), and kept the translation spans. Closing this thread. @amir-zeldes let me know if you anticipate any problems.

**Comment by amir-zeldes** [comment]
No problems from my end, though I'm not sure if the value is not confusing - if there's a p_source which tells us the source it sounds like there might be another layer called p (for which this layer indicates the source). It's not technical problem in any case, since this layer is not being visualized in a special way in ANNIS.

**Comment by ctschroeder** [comment]
Ok thanks! I chose that from the options I listed upthread since it sounded like it didn’t matter to you which I chose. If you decide something is better then please ping me. If it’s all good Aphou 1 is ready for the next round and the others will soon follow. Thanks again!!

**Comment by amir-zeldes** [comment]
No, it doesn't really matter one way or another, it should be fine. Thanks!
